name: Build

on:
  push:
    branches: [stable]
  pull_request:
    branches: [stable]
    paths:
      - ".github/workflows/build.yml"
      - "Bon Appetit/**"
      - "Bon Appetit.xcodeproj/**"

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Switch version of Xcode
        run: sudo xcode-select --switch "/Applications/Xcode_12.app/Contents/Developer"

      - name: Build
        run: set -o pipefail && xcodebuild clean build -project "Bon Appetit.xcodeproj" -scheme "Bon Appetit" -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO | xcpretty --simple
